export const REQUEST_PRODUCT = 'REQUEST_PRODUCT';
export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED';

export const REQUEST_PRODUCT_INFORMATION = 'REQUEST_PRODUCT_INFORMATION';
export const FETCH_PRODUCT_INFORMATION = "FETCH_PRODUCT_INFORMATION";
export const ADD_PRODUCT_INFORMATION_SUCCESS = "ADD_PRODUCT_INFORMATION";
export const FETCH_PRODUCT_INFORMATION_FAILED = 'FETCH_PRODUCTS_FAILED';


export const ADD_LAST_FUNCTION = "ADD_LAST_FUNCTION";

export const REQUEST_DELETE_PRODUCT_IN_CART = 'REQUEST_DELETE_PRODUCT_IN_CART';
export const REQUEST_EXECUTE_PRODUCTS_IN_CART = 'REQUEST_EXECUTE_PRODUCTS_IN_CART';
export const REQUEST_ADD_PRODUCT_IN_CART = 'REQUEST_ADD_PRODUCT_IN_CART';
export const FETCH_USERS_PRODUCTS_IN_CART = "FETCH_USERS_PRODUCTS_IN_CART";
export const ADD_USERS_PRODUCTS_IN_CART = "ADD_USERS_PRODUCTS_IN_CART";
export const FETCH_USERS_PRODUCTS_IN_CART_FAILED = 'FETCH_USERS_PRODUCTS_IN_CART_FAILED';
export const SET_RESPONSE_NOTIFICATION_IN_CART = 'SET_RESPONSE_NOTIFICATION_IN_CART';
export const EXECUTE_USERS_PRODUCTS_IN_CART = "EXECUTE_USERS_PRODUCTS_IN_CART";
export const REQUEST_GET_PRODUCTS_IN_CART = 'REQUEST_GET_PRODUCTS_IN_CART';

export const REQUEST_VOTE_PRODUCT = 'REQUEST_VOTE_PRODUCT';


export const ADD_INFO_PRODUCTS = "ADD_INFO_USERS_PRODUCTS";


